import { SalesByRepDataSchema } from "@/types";

// Mock data for mini charts - static data showing upward trend
export const salesChartData = [
    { name: 'Day 1', value: 45 },
    { name: 'Day 2', value: 52 },
    { name: 'Day 3', value: 58 },
    { name: 'Day 4', value: 65 },
    { name: 'Day 5', value: 72 },
    { name: 'Day 6', value: 78 },
    { name: 'Day 7', value: 85 },
];

export const ytdChartData = [
    { name: 'Day 1', value: 48 },
    { name: 'Day 2', value: 55 },
    { name: 'Day 3', value: 62 },
    { name: 'Day 4', value: 68 },
    { name: 'Day 5', value: 75 },
    { name: 'Day 6', value: 82 },
    { name: 'Day 7', value: 90 },
];

export const yoyChartData = [
    { name: 'Day 1', value: 50 },
    { name: 'Day 2', value: 57 },
    { name: 'Day 3', value: 64 },
    { name: 'Day 4', value: 71 },
    { name: 'Day 5', value: 78 },
    { name: 'Day 6', value: 85 },
    { name: 'Day 7', value: 92 },
];

export const tourRevenueData = [
    {
        tour: 'Live Nation Concerts',
        currentMonth: 125000,
        ytd: 980000,
        total: 1105000,
    },
    {
        tour: 'Live Nation Chicago',
        currentMonth: 98000,
        ytd: 820000,
        total: 918000,
    },
    { tour: 'Red Housing', currentMonth: 87000, ytd: 720000, total: 807000 },
    {
        tour: 'The Boys From The County Hell',
        currentMonth: 76000,
        ytd: 650000,
        total: 726000,
    },
    { tour: 'Housemath', currentMonth: 68000, ytd: 590000, total: 658000 },
    { tour: 'Westlife 2024', currentMonth: 62000, ytd: 540000, total: 602000 },
    { tour: "A Doll's 2024", currentMonth: 58000, ytd: 495000, total: 553000 },
    { tour: 'Descendants', currentMonth: 54000, ytd: 460000, total: 514000 },
    { tour: 'Opzn 2024', currentMonth: 51000, ytd: 430000, total: 481000 },
    { tour: 'Bon Jovi 2024', currentMonth: 48000, ytd: 410000, total: 458000 },
    {
        tour: 'Demi Lovato Tour',
        currentMonth: 45000,
        ytd: 385000,
        total: 430000,
    },
    { tour: 'Diesel Ltd', currentMonth: 43000, ytd: 365000, total: 408000 },
    { tour: 'Matt Rife 2024', currentMonth: 41000, ytd: 350000, total: 391000 },
    { tour: 'Luke Life Girl', currentMonth: 39000, ytd: 330000, total: 369000 },
    {
        tour: 'Renee Rapp - Snow Tour',
        currentMonth: 37000,
        ytd: 315000,
        total: 352000,
    },
    {
        tour: 'Lady Gaga: chromatica ball',
        currentMonth: 35000,
        ytd: 295000,
        total: 330000,
    },
    {
        tour: 'Christina Aguilera',
        currentMonth: 34000,
        ytd: 285000,
        total: 319000,
    },
    {
        tour: 'The Streets 2024',
        currentMonth: 32000,
        ytd: 270000,
        total: 302000,
    },
    {
        tour: 'Rock In The Park',
        currentMonth: 31000,
        ytd: 260000,
        total: 291000,
    },
    {
        tour: 'Playboi Carti Tour',
        currentMonth: 29000,
        ytd: 245000,
        total: 274000,
    },
    { tour: 'Rüfüs 2025', currentMonth: 28000, ytd: 235000, total: 263000 },
    {
        tour: 'Earth, Wind & Fire',
        currentMonth: 27000,
        ytd: 225000,
        total: 252000,
    },
    { tour: 'Cosmic Girl', currentMonth: 26000, ytd: 215000, total: 241000 },
];

// Mock users for clients and collaborators
export const mockUsers = [
    {
        id: 1,
        name: 'Sarah Johnson',
        email: 'sarah.johnson@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Sarah',
        last_name: 'Johnson',
        assetsAssigned: 45,
        assetsUploaded: 38,
        rolling30DayAccuracy: 87,
        trend: { direction: 'up' as const, percentage: 5 },
    },
    {
        id: 2,
        name: 'Michael Chen',
        email: 'michael.chen@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Michael',
        last_name: 'Chen',
        assetsAssigned: 52,
        assetsUploaded: 44,
        rolling30DayAccuracy: 92,
        trend: { direction: 'up' as const, percentage: 8 },
    },
    {
        id: 3,
        name: 'Emily Rodriguez',
        email: 'emily.rodriguez@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Emily',
        last_name: 'Rodriguez',
        assetsAssigned: 38,
        assetsUploaded: 32,
        rolling30DayAccuracy: 79,
        trend: { direction: 'down' as const, percentage: 3 },
    },
    {
        id: 4,
        name: 'David Williams',
        email: 'david.williams@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'David',
        last_name: 'Williams',
        assetsAssigned: 61,
        assetsUploaded: 55,
        rolling30DayAccuracy: 95,
        trend: { direction: 'up' as const, percentage: 12 },
    },
    {
        id: 5,
        name: 'Jessica Martinez',
        email: 'jessica.martinez@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Jessica',
        last_name: 'Martinez',
        assetsAssigned: 41,
        assetsUploaded: 36,
        rolling30DayAccuracy: 83,
        trend: { direction: 'up' as const, percentage: 6 },
    },
];

// Mock pending orders grouped by artist
export const pendingOrdersData = [
    {
        id: '1',
        artist: 'Matt Rife',
        name: 'Demo',
        venue: '',
        dueDate: '',
        client: mockUsers[0],
        collaborators: [mockUsers[0]],
        status: 'completed',
        isGroupHeader: true,
    },
    {
        id: '2',
        artist: 'Matt Rife',
        name: 'New York, NY',
        venue: 'Maddison Square Garden',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'edit',
        isGroupHeader: false,
    },
    {
        id: '3',
        artist: 'Matt Rife',
        name: 'Dallas, TX',
        venue: 'Sunset Amphitheater at McKinney, Texas',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'in-progress',
        isGroupHeader: false,
    },
    {
        id: '4',
        artist: 'Matt Rife',
        name: 'Oklahoma City, OK',
        venue: 'Alys Robinson Stephens Performing Arts Center',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'in-progress',
        isGroupHeader: false,
    },
    {
        id: '5',
        artist: 'Matt Rife',
        name: 'Chicago, IL',
        venue: 'The Coca Cola Charlotte Harbor Event and Conference Center',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'paused',
        isGroupHeader: false,
    },
    {
        id: '6',
        artist: 'Eagles',
        name: 'Los Angeles, CA',
        venue: 'Hollywood Bowl',
        dueDate: 'Nov 15',
        client: mockUsers[3],
        collaborators: [mockUsers[3], mockUsers[4]],
        status: 'in-progress',
        isGroupHeader: false,
    },
    {
        id: '7',
        artist: 'Eagles',
        name: 'San Francisco, CA',
        venue: 'Chase Center',
        dueDate: 'Nov 16',
        client: mockUsers[3],
        collaborators: [mockUsers[3], mockUsers[4]],
        status: 'pending',
        isGroupHeader: false,
    },
];

export const salesByRepData: SalesByRepDataSchema[] = [
    {
        rep: 'Russel',
        currentMonth: 125000,
        currentMonthChange: { direction: 'up', percentage: 12 },
        ytd: 980000,
        ytdChange: { direction: 'up', percentage: 8 },
        total: 1105000,
    },
    {
        rep: 'James',
        currentMonth: 98000,
        currentMonthChange: { direction: 'up', percentage: 15 },
        ytd: 820000,
        ytdChange: { direction: 'up', percentage: 10 },
        total: 918000,
    },
    {
        rep: 'Jordan',
        currentMonth: -74000,
        currentMonthChange: { direction: 'down', percentage: 5 },
        ytd: -74000,
        ytdChange: { direction: 'up', percentage: 6 },
        total: -74000,
    },
];
