import {
    SalesByRepDataSchema,
    type Company,
    type Invoice,
    type InvoiceItem,
} from '@/types';

// Mock data for mini charts - static data showing upward trend
export const salesChartData = [
    { name: 'Day 1', value: 45 },
    { name: 'Day 2', value: 52 },
    { name: 'Day 3', value: 58 },
    { name: 'Day 4', value: 65 },
    { name: 'Day 5', value: 72 },
    { name: 'Day 6', value: 78 },
    { name: 'Day 7', value: 85 },
];

export const ytdChartData = [
    { name: 'Day 1', value: 48 },
    { name: 'Day 2', value: 55 },
    { name: 'Day 3', value: 62 },
    { name: 'Day 4', value: 68 },
    { name: 'Day 5', value: 75 },
    { name: 'Day 6', value: 82 },
    { name: 'Day 7', value: 90 },
];

export const yoyChartData = [
    { name: 'Day 1', value: 50 },
    { name: 'Day 2', value: 57 },
    { name: 'Day 3', value: 64 },
    { name: 'Day 4', value: 71 },
    { name: 'Day 5', value: 78 },
    { name: 'Day 6', value: 85 },
    { name: 'Day 7', value: 92 },
];

export const tourRevenueData = [
    {
        tour: 'Live Nation Concerts',
        currentMonth: 125000,
        ytd: 980000,
        total: 1105000,
    },
    {
        tour: 'Live Nation Chicago',
        currentMonth: 98000,
        ytd: 820000,
        total: 918000,
    },
    { tour: 'Red Housing', currentMonth: 87000, ytd: 720000, total: 807000 },
    {
        tour: 'The Boys From The County Hell',
        currentMonth: 76000,
        ytd: 650000,
        total: 726000,
    },
    { tour: 'Housemath', currentMonth: 68000, ytd: 590000, total: 658000 },
    { tour: 'Westlife 2024', currentMonth: 62000, ytd: 540000, total: 602000 },
    { tour: "A Doll's 2024", currentMonth: 58000, ytd: 495000, total: 553000 },
    { tour: 'Descendants', currentMonth: 54000, ytd: 460000, total: 514000 },
    { tour: 'Opzn 2024', currentMonth: 51000, ytd: 430000, total: 481000 },
    { tour: 'Bon Jovi 2024', currentMonth: 48000, ytd: 410000, total: 458000 },
    {
        tour: 'Demi Lovato Tour',
        currentMonth: 45000,
        ytd: 385000,
        total: 430000,
    },
    { tour: 'Diesel Ltd', currentMonth: 43000, ytd: 365000, total: 408000 },
    { tour: 'Matt Rife 2024', currentMonth: 41000, ytd: 350000, total: 391000 },
    { tour: 'Luke Life Girl', currentMonth: 39000, ytd: 330000, total: 369000 },
    {
        tour: 'Renee Rapp - Snow Tour',
        currentMonth: 37000,
        ytd: 315000,
        total: 352000,
    },
    {
        tour: 'Lady Gaga: chromatica ball',
        currentMonth: 35000,
        ytd: 295000,
        total: 330000,
    },
    {
        tour: 'Christina Aguilera',
        currentMonth: 34000,
        ytd: 285000,
        total: 319000,
    },
    {
        tour: 'The Streets 2024',
        currentMonth: 32000,
        ytd: 270000,
        total: 302000,
    },
    {
        tour: 'Rock In The Park',
        currentMonth: 31000,
        ytd: 260000,
        total: 291000,
    },
    {
        tour: 'Playboi Carti Tour',
        currentMonth: 29000,
        ytd: 245000,
        total: 274000,
    },
    { tour: 'Rüfüs 2025', currentMonth: 28000, ytd: 235000, total: 263000 },
    {
        tour: 'Earth, Wind & Fire',
        currentMonth: 27000,
        ytd: 225000,
        total: 252000,
    },
    { tour: 'Cosmic Girl', currentMonth: 26000, ytd: 215000, total: 241000 },
];

// Mock users for clients and collaborators
export const mockUsers = [
    {
        id: 1,
        name: 'Sarah Johnson',
        email: 'sarah.johnson@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Sarah',
        last_name: 'Johnson',
        assetsAssigned: 45,
        assetsUploaded: 38,
        rolling30DayAccuracy: 87,
        trend: { direction: 'up' as const, percentage: 5 },
    },
    {
        id: 2,
        name: 'Michael Chen',
        email: 'michael.chen@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Michael',
        last_name: 'Chen',
        assetsAssigned: 52,
        assetsUploaded: 44,
        rolling30DayAccuracy: 92,
        trend: { direction: 'up' as const, percentage: 8 },
    },
    {
        id: 3,
        name: 'Emily Rodriguez',
        email: 'emily.rodriguez@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Emily',
        last_name: 'Rodriguez',
        assetsAssigned: 38,
        assetsUploaded: 32,
        rolling30DayAccuracy: 79,
        trend: { direction: 'down' as const, percentage: 3 },
    },
    {
        id: 4,
        name: 'David Williams',
        email: 'david.williams@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'David',
        last_name: 'Williams',
        assetsAssigned: 61,
        assetsUploaded: 55,
        rolling30DayAccuracy: 95,
        trend: { direction: 'up' as const, percentage: 12 },
    },
    {
        id: 5,
        name: 'Jessica Martinez',
        email: 'jessica.martinez@example.com',
        avatar: null,
        email_verified_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        first_name: 'Jessica',
        last_name: 'Martinez',
        assetsAssigned: 41,
        assetsUploaded: 36,
        rolling30DayAccuracy: 83,
        trend: { direction: 'up' as const, percentage: 6 },
    },
];

// Mock pending orders grouped by artist
export const pendingOrdersData = [
    {
        id: '1',
        artist: 'Matt Rife',
        name: 'Demo',
        venue: '',
        dueDate: '',
        client: mockUsers[0],
        collaborators: [mockUsers[0]],
        status: 'completed',
        isGroupHeader: true,
    },
    {
        id: 2,
        artist: 'Matt Rife',
        name: 'New York, NY',
        venue: 'Maddison Square Garden',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'edit',
        isGroupHeader: false,
    },
    {
        id: 3,
        artist: 'Matt Rife',
        name: 'Dallas, TX',
        venue: 'Sunset Amphitheater at McKinney, Texas',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'in-progress',
        isGroupHeader: false,
    },
    {
        id: 4,
        artist: 'Matt Rife',
        name: 'Oklahoma City, OK',
        venue: 'Alys Robinson Stephens Performing Arts Center',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'in-progress',
        isGroupHeader: false,
    },
    {
        id: 5,
        artist: 'Matt Rife',
        name: 'Chicago, IL',
        venue: 'The Coca Cola Charlotte Harbor Event and Conference Center',
        dueDate: 'Nov 8',
        client: mockUsers[0],
        collaborators: [mockUsers[0], mockUsers[1], mockUsers[2]],
        status: 'paused',
        isGroupHeader: false,
    },
    {
        id: '6',
        artist: 'Eagles',
        name: 'Los Angeles, CA',
        venue: 'Hollywood Bowl',
        dueDate: 'Nov 15',
        client: mockUsers[3],
        collaborators: [mockUsers[3], mockUsers[4]],
        status: 'in-progress',
        isGroupHeader: false,
    },
    {
        id: '7',
        artist: 'Eagles',
        name: 'San Francisco, CA',
        venue: 'Chase Center',
        dueDate: 'Nov 16',
        client: mockUsers[3],
        collaborators: [mockUsers[3], mockUsers[4]],
        status: 'pending',
        isGroupHeader: false,
    },
];

export const salesByRepData: SalesByRepDataSchema[] = [
    {
        rep: 'Russel',
        currentMonth: 125000,
        currentMonthChange: { direction: 'up', percentage: 12 },
        ytd: 980000,
        ytdChange: { direction: 'up', percentage: 8 },
        total: 1105000,
    },
    {
        rep: 'James',
        currentMonth: 98000,
        currentMonthChange: { direction: 'up', percentage: 15 },
        ytd: 820000,
        ytdChange: { direction: 'up', percentage: 10 },
        total: 918000,
    },
    {
        rep: 'Jordan',
        currentMonth: -74000,
        currentMonthChange: { direction: 'down', percentage: 5 },
        ytd: -74000,
        ytdChange: { direction: 'up', percentage: 6 },
        total: -74000,
    },
];

// Mock company data
export const companiesData: Company[] = [
    {
        id: 1,
        companyName: 'CIRQUE DU SOLEIL AMERICA NEWCO,',
        address: '1151 Grier Drive, Suite C\nLas Vegas, NV 964075, USA',
    },
    {
        id: 2,
        companyName: 'Live Nation Entertainment, Inc.',
        address: '9348 Civic Center Drive\nBeverly Hills, CA 90210, USA',
    },
    {
        id: 3,
        companyName: 'Matt Rife Productions',
        address: '123 Entertainment Blvd\nLos Angeles, CA 90028, USA',
    },
    {
        id: 4,
        companyName: 'Bon Jovi Touring, LLC',
        address: '456 Music Avenue\nNew York, NY 10001, USA',
    },
    {
        id: 5,
        companyName: 'Demi Lovato Entertainment',
        address: '789 Star Street\nLos Angeles, CA 90069, USA',
    },
    {
        id: 6,
        companyName: 'Renee Rapp Touring',
        address: '321 Performance Lane\nNashville, TN 37203, USA',
    },
];

// Mock invoice data based on image
export const invoicesData: Invoice[] = [
    {
        id: 1,
        invoiceNumber: '974658',
        date: '11/06/24',
        tour: 'Cirque du Soleil Portfolio',
        market: 'Portfolio Sizzle',
        venue: 'N/A',
        amount: 8750.0,
        daysToShow: -40,
        showDate: new Date('2024-10-27'),
        isDeleted: false,
        user_id: 1,
        company_id: 1,
        invoiceReleaseDate: '2024-10-27',
        invoiceDueDate: '2024-11-27',
        clientReference: 'Generic Pre Sale',
    },
    {
        id: 2,
        invoiceNumber: '980043',
        date: '9/30/25',
        tour: 'Cirque du Soleil Echo',
        market: 'San Francisco, CA',
        venue: 'Oracle Park',
        amount: 7692.44,
        daysToShow: -2,
        showDate: new Date('2025-09-28'),
        isDeleted: false,
        user_id: 2,
        company_id: 1,
        invoiceReleaseDate: '2025-09-28',
        invoiceDueDate: '2025-10-28',
        clientReference: 'Amex Pre Sale',
    },
    {
        id: 3,
        invoiceNumber: '984958',
        date: '11/06/24',
        tour: 'Cirque du Soleil Echo',
        market: 'Dallas, TX',
        venue: 'American Airlines Center',
        amount: 9571.78,
        daysToShow: 29,
        showDate: new Date('2025-01-15'),
        isDeleted: false,
        user_id: 3,
        company_id: 1,
        invoiceReleaseDate: '2024-12-10',
        invoiceDueDate: '2025-01-10',
        clientReference: 'Generic Spots',
    },
    {
        id: 4,
        invoiceNumber: '981873',
        date: '9/30/25',
        tour: 'Cirque du Soleil Echo',
        market: 'Seattle, WA',
        venue: "King County's Marymoor Park",
        amount: 9205.24,
        daysToShow: 62,
        showDate: new Date('2025-02-17'),
        isDeleted: false,
        user_id: 4,
        company_id: 1,
        invoiceReleaseDate: '2025-01-15',
        invoiceDueDate: '2025-02-15',
        clientReference: 'Generic Pre sale',
    },
    {
        id: 5,
        invoiceNumber: '981873',
        date: '9/30/25',
        tour: 'Cirque du Soleil Echo',
        market: 'Seattle, WA',
        venue: "King County's Marymoor Park",
        amount: 3205.24,
        daysToShow: 0,
        showDate: new Date('2025-02-17'),
        isDeleted: true,
        user_id: 5,
        company_id: 1,
        invoiceReleaseDate: '2025-01-15',
        invoiceDueDate: '2025-02-15',
        clientReference: 'Generic Pre sale',
    },
    {
        id: 6,
        invoiceNumber: '985234',
        date: '10/15/24',
        tour: 'Live Nation Concerts',
        market: 'Los Angeles, CA',
        venue: 'Hollywood Bowl',
        amount: 9230.5,
        daysToShow: 15,
        showDate: new Date('2025-01-30'),
        isDeleted: false,
        user_id: 1,
        company_id: 2,
        invoiceReleaseDate: '2024-12-15',
        invoiceDueDate: '2025-01-15',
        clientReference: 'VIP Pre Sale',
    },
    {
        id: 7,
        invoiceNumber: '986789',
        date: '10/22/24',
        tour: 'Matt Rife 2024',
        market: 'Chicago, IL',
        venue: 'United Center',
        amount: 8150.0,
        daysToShow: 45,
        showDate: new Date('2025-02-12'),
        isDeleted: false,
        user_id: 2,
        company_id: 3,
        invoiceReleaseDate: '2024-12-22',
        invoiceDueDate: '2025-01-22',
        clientReference: 'Early Bird Sale',
    },
    {
        id: 8,
        invoiceNumber: '987456',
        date: '11/01/24',
        tour: 'Bon Jovi 2024',
        market: 'New York, NY',
        venue: 'Madison Square Garden',
        amount: 9890.25,
        daysToShow: 78,
        showDate: new Date('2025-03-05'),
        isDeleted: false,
        user_id: 3,
        company_id: 4,
        invoiceReleaseDate: '2025-01-01',
        invoiceDueDate: '2025-02-01',
        clientReference: 'Fan Club Pre Sale',
    },
    {
        id: 9,
        invoiceNumber: '988123',
        date: '11/10/24',
        tour: 'Demi Lovato Tour',
        market: 'Miami, FL',
        venue: 'American Airlines Arena',
        amount: 8457.0,
        daysToShow: 92,
        showDate: new Date('2025-03-20'),
        isDeleted: false,
        user_id: 4,
        company_id: 5,
        invoiceReleaseDate: '2025-01-10',
        invoiceDueDate: '2025-02-10',
        clientReference: 'General Sale',
    },
    {
        id: 10,
        invoiceNumber: '989567',
        date: '11/18/24',
        tour: 'Renee Rapp - Snow Tour',
        market: 'Boston, MA',
        venue: 'TD Garden',
        amount: 6945.33,
        daysToShow: 105,
        showDate: new Date('2025-04-02'),
        isDeleted: false,
        user_id: 5,
        company_id: 6,
        invoiceReleaseDate: '2025-01-18',
        invoiceDueDate: '2025-02-18',
        clientReference: 'Presale Code',
    },
];

// Mock invoice items data
export const invoiceItemsData: InvoiceItem[] = [
    // Invoice 1 - 1 item (total: 8750.0)
    {
        id: 1,
        invoice_id: 1,
        code: 'Big Top',
        description: 'Large format tent structure rental',
        quantity: 1,
        price: 8750.0,
    },
    // Invoice 2 - 2 items (total: 7692.44)
    {
        id: 2,
        invoice_id: 2,
        code: 'TV',
        description: 'LED display screen rental - 65 inch',
        quantity: 2,
        price: 2500.0,
    },
    {
        id: 3,
        invoice_id: 2,
        code: 'Print',
        description: 'Printed promotional materials and banners',
        quantity: 12,
        price: 224.37,
    },
    // Invoice 3 - 6 items (total: 9571.78)
    {
        id: 4,
        invoice_id: 3,
        code: 'Banner',
        description: 'Large format vinyl banner - 10ft x 20ft',
        quantity: 2,
        price: 450.0,
    },
    {
        id: 5,
        invoice_id: 3,
        code: 'Signage',
        description: 'Directional signage set',
        quantity: 8,
        price: 125.5,
    },
    {
        id: 6,
        invoice_id: 3,
        code: 'Digital Display',
        description: 'Digital display board rental',
        quantity: 1,
        price: 3500.0,
    },
    {
        id: 7,
        invoice_id: 3,
        code: 'Poster',
        description: 'Event posters - 24x36 inch',
        quantity: 50,
        price: 12.5,
    },
    {
        id: 8,
        invoice_id: 3,
        code: 'Flyer',
        description: 'Promotional flyers - 8.5x11 inch',
        quantity: 500,
        price: 0.35,
    },
    {
        id: 9,
        invoice_id: 3,
        code: 'Backdrop',
        description: 'Stage backdrop - custom printed',
        quantity: 1,
        price: 3367.78,
    },
    // Invoice 4 - 8 items (total: 9205.24)
    {
        id: 10,
        invoice_id: 4,
        code: 'LED Screen',
        description: 'LED video wall rental - 10x15ft',
        quantity: 1,
        price: 1500.0,
    },
    {
        id: 11,
        invoice_id: 4,
        code: 'TV',
        description: 'TV monitor rental - 55 inch',
        quantity: 2,
        price: 800.0,
    },
    {
        id: 12,
        invoice_id: 4,
        code: 'Banner',
        description: 'Vinyl banner - 8ft x 16ft',
        quantity: 3,
        price: 320.0,
    },
    {
        id: 13,
        invoice_id: 4,
        code: 'Signage',
        description: 'Wayfinding signage package',
        quantity: 15,
        price: 95.0,
    },
    {
        id: 14,
        invoice_id: 4,
        code: 'Poster',
        description: 'Event posters - 18x24 inch',
        quantity: 30,
        price: 8.75,
    },
    {
        id: 15,
        invoice_id: 4,
        code: 'Stage Set',
        description: 'Stage set pieces and props',
        quantity: 1,
        price: 1994.74,
    },
    {
        id: 16,
        invoice_id: 4,
        code: 'Backdrop',
        description: 'Custom printed backdrop - 20x30ft',
        quantity: 1,
        price: 1205.0,
    },
    {
        id: 17,
        invoice_id: 4,
        code: 'Print',
        description: 'Printed marketing materials',
        quantity: 20,
        price: 12.9,
    },
    // Invoice 5 - 1 item (deleted invoice) (total: 3205.24)
    {
        id: 18,
        invoice_id: 5,
        code: 'Billboard',
        description: 'Outdoor billboard advertising',
        quantity: 1,
        price: 3205.24,
    },
    // Invoice 6 - 7 items (total: 9230.5)
    {
        id: 19,
        invoice_id: 6,
        code: 'Big Top',
        description: 'Large tent structure with setup',
        quantity: 1,
        price: 1500.0,
    },
    {
        id: 20,
        invoice_id: 6,
        code: 'LED Screen',
        description: 'LED video display - 12x20ft',
        quantity: 1,
        price: 1200.0,
    },
    {
        id: 21,
        invoice_id: 6,
        code: 'TV',
        description: 'TV monitor rental - 75 inch',
        quantity: 2,
        price: 800.0,
    },
    {
        id: 22,
        invoice_id: 6,
        code: 'Banner',
        description: 'Custom vinyl banners - various sizes',
        quantity: 5,
        price: 380.0,
    },
    {
        id: 23,
        invoice_id: 6,
        code: 'Signage',
        description: 'Event signage package',
        quantity: 12,
        price: 110.0,
    },
    {
        id: 24,
        invoice_id: 6,
        code: 'Poster',
        description: 'Event posters - 24x36 inch',
        quantity: 40,
        price: 11.25,
    },
    {
        id: 25,
        invoice_id: 6,
        code: 'Stage Set',
        description: 'Stage set design and installation',
        quantity: 1,
        price: 1260.5,
    },
    // Invoice 7 - 5 items (total: 8150.0)
    {
        id: 26,
        invoice_id: 7,
        code: 'Digital Display',
        description: 'Digital signage system rental',
        quantity: 2,
        price: 1200.0,
    },
    {
        id: 27,
        invoice_id: 7,
        code: 'TV',
        description: 'TV monitor rental - 65 inch',
        quantity: 3,
        price: 600.0,
    },
    {
        id: 28,
        invoice_id: 7,
        code: 'Banner',
        description: 'Vinyl banner - 12ft x 24ft',
        quantity: 2,
        price: 550.0,
    },
    {
        id: 29,
        invoice_id: 7,
        code: 'Print',
        description: 'Printed promotional materials',
        quantity: 25,
        price: 15.0,
    },
    {
        id: 30,
        invoice_id: 7,
        code: 'Backdrop',
        description: 'Custom stage backdrop - 15x25ft',
        quantity: 1,
        price: 2475.0,
    },
    // Invoice 8 - 9 items (total: 9890.25)
    {
        id: 31,
        invoice_id: 8,
        code: 'Big Top',
        description: 'Premium tent structure rental',
        quantity: 1,
        price: 1500.0,
    },
    {
        id: 32,
        invoice_id: 8,
        code: 'LED Screen',
        description: 'LED video wall - 15x25ft',
        quantity: 1,
        price: 1100.0,
    },
    {
        id: 33,
        invoice_id: 8,
        code: 'TV',
        description: 'TV monitor rental - 85 inch',
        quantity: 2,
        price: 650.0,
    },
    {
        id: 34,
        invoice_id: 8,
        code: 'Banner',
        description: 'Custom banners - various sizes',
        quantity: 4,
        price: 240.0,
    },
    {
        id: 35,
        invoice_id: 8,
        code: 'Signage',
        description: 'Comprehensive signage package',
        quantity: 15,
        price: 85.0,
    },
    {
        id: 36,
        invoice_id: 8,
        code: 'Poster',
        description: 'Event posters - 24x36 inch',
        quantity: 50,
        price: 10.0,
    },
    {
        id: 37,
        invoice_id: 8,
        code: 'Flyer',
        description: 'Promotional flyers - 8.5x11 inch',
        quantity: 800,
        price: 0.35,
    },
    {
        id: 38,
        invoice_id: 8,
        code: 'Stage Set',
        description: 'Premium stage set design',
        quantity: 1,
        price: 1500.0,
    },
    {
        id: 39,
        invoice_id: 8,
        code: 'Backdrop',
        description: 'Custom printed backdrop - 25x40ft',
        quantity: 1,
        price: 1515.25,
    },
    // Invoice 9 - 3 items (total: 8457.00)
    {
        id: 40,
        invoice_id: 9,
        code: 'Digital Display',
        description: 'Digital display board rental',
        quantity: 1,
        price: 3000.0,
    },
    {
        id: 41,
        invoice_id: 9,
        code: 'TV',
        description: 'TV monitor rental - 55 inch',
        quantity: 4,
        price: 1200.0,
    },
    {
        id: 42,
        invoice_id: 9,
        code: 'Print',
        description: 'Printed marketing materials package',
        quantity: 30,
        price: 21.9,
    },
    // Invoice 10 - 4 items (total: 6945.33)
    {
        id: 43,
        invoice_id: 10,
        code: 'Banner',
        description: 'Vinyl banner - 10ft x 20ft',
        quantity: 3,
        price: 420.0,
    },
    {
        id: 44,
        invoice_id: 10,
        code: 'Signage',
        description: 'Event signage set',
        quantity: 10,
        price: 105.0,
    },
    {
        id: 45,
        invoice_id: 10,
        code: 'Poster',
        description: 'Event posters - 18x24 inch',
        quantity: 35,
        price: 9.5,
    },
    {
        id: 46,
        invoice_id: 10,
        code: 'Backdrop',
        description: 'Stage backdrop - 12x20ft',
        quantity: 1,
        price: 4302.83,
    },
];
